const sitesDatabase = [
    ... // existing attractions
    {
        id: 'lipetskoe-more',
        name: 'Липецкое море',
        coords: [52.4, 39.8],
        region: 'Липецкий район',
        description: 'Искусственное водохранилище площадью 10 км². Популярное место для отдыха, рыбалки и водного спорта.',
        fullDescription: '',
        type: '',
        category: '',
        area: '',
        founded: '',
        species: '',
        activities: '',
        howToReach: '',
        image: '',
        gallery: [],
        status: '',
        importance: '',
    },
    {
        id: 'sosna-rocks',
        name: 'Скальные образования на реке Сосна',
        coords: [52.3, 39.0],
        region: 'Липецкий район',
        description: 'Живописные скальные выступы на берегах реки. Место популярное среди туристов и любителей природы.',
        fullDescription: '',
        type: '',
        category: '',
        area: '',
        founded: '',
        species: '',
        activities: '',
        howToReach: '',
        image: '',
        gallery: [],
        status: '',
        importance: '',
    },
    {
        id: 'chaloe-lake',
        name: 'Озеро Чалое',
        coords: [52.65, 39.2],
        region: 'Данковский район',
        description: 'Небольшое карстовое озеро с кристально чистой водой. Место обитания редких водных раст��ний.',
        fullDescription: '',
        type: '',
        category: '',
        area: '',
        founded: '',
        species: '',
        activities: '',
        howToReach: '',
        image: '',
        gallery: [],
        status: '',
        importance: '',
    },
    {
        id: 'olshinsky-forest',
        name: 'Лес Ольшинский',
        coords: [52.8, 39.1],
        region: 'Добровский район',
        description: 'Старовозрастный лес с уникальной экосистемой. Место для пешеходных маршрутов и наблюдения за природой.',
        fullDescription: '',
        type: '',
        category: '',
        area: '',
        founded: '',
        species: '',
        activities: '',
        howToReach: '',
        image: '',
        gallery: [],
        status: '',
        importance: '',
    },
    {
        id: 'krasnomostskoe-spring',
        name: 'Святой источник Красномостское',
        coords: [52.5, 38.8],
        region: 'Грязинский район',
        description: 'Природный источник с кристально чистой холодной водой. Место паломничества верующих.',
        fullDescription: '',
        type: '',
        category: '',
        area: '',
        founded: '',
        species: '',
        activities: '',
        howToReach: '',
        image: '',
        gallery: [],
        status: '',
        importance: '',
    },
    {
        id: 'slonikov-log',
        name: 'Останцы Слониковский Лог',
        coords: [52.7, 38.6],
        region: 'Становлянский район',
        description: 'Уникальные геологические образования в виде останцев. Интересный объект для геологов и туристов.',
        fullDescription: '',
        type: '',
        category: '',
        area: '',
        founded: '',
        species: '',
        activities: '',
        howToReach: '',
        image: '',
        gallery: [],
        status: '',
        importance: '',
    },
];